[build]
providers = ["php"]

[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.json"]

[phases.install]
cmds = ["echo 'Installing dependencies...'", "ls -la"]

[start]
cmd = "./start.sh"