[build]
builder = "heroku/buildpacks:20"
buildpacks = ["heroku/php"]

[deploy]
numReplicas = 1
sleepOnDeploy = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
APP_ENV = "production"